### ISSUE TITLE
STS vs Retrieval

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#101]
So atm. we have implemented Swedn (news summarisation) as an STS and as a retrieval task:

<img width="583" alt="Screenshot 2024-01-26 at 11 13 53" src="https://github.com/KennethEnevoldsen/scandinavian-embedding-benchmark/assets/23721977/335fd965-ee27-407c-830f-2815d98aa9c7">

The scores seems to favour the retrieval task (as it has more variance). This seems like a good reason to choose the retrieval task in general. Actually I see quite few reasons to formulate it as an STS task. So I am considering removing the task SwednSTS?

@Muennighoff, @x-tabdeveloping just checking in with you guys before I do so?

**Comment by Muennighoff** [comment]
Interesting! I think this analysis is also worth putting in the paper. I agree that Retrieval seems more suitable.

**Comment by x-tabdeveloping** [comment]
Hmm I mean both would make sense. Which are you using as a query and which one as a document for retrieval?

**Comment by KennethEnevoldsen** [comment]
Retrieval: headline retrieves article and summary.

STS: Positive pay is summary and corresponding article. Negative pair is summary and non-corresponding article.

**Comment by KennethEnevoldsen** [comment]
It might be that it STS is easier simply due to it having longer documents to work with.

**Comment by KennethEnevoldsen** [comment]
<img width="586" alt="Screenshot 2024-01-26 at 13 09 19" src="https://github.com/KennethEnevoldsen/scandinavian-embedding-benchmark/assets/23721977/0c0362f0-0a05-469b-a171-f167b829908c">

^so still more of a spread between models. But Swedn seems to saturate. It might also be valid to include both tasks?

**Comment by x-tabdeveloping** [comment]
Hmmm I think I would just include summary-article retrieval. It makes sense and has high spread. I think including the same dataset with two tasks is a bit problematic.

**Comment by KennethEnevoldsen** [comment]
Perfect I have added an issue #107
