### ISSUE TITLE
rerun e5 and cohere  with custom embeddings

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#102]
Seems like we were a bit too hasty with merged #92. We still have to update the scores (at least to see if everything works correctly)

**Comment by x-tabdeveloping** [comment]
I don't think it was too hasty, I know for a fact that it works correctly, I did some tests locally with some debugging statements and in asymmetric tasks the correct functions are getting called. I agree that we should update the results though.

**Comment by KennethEnevoldsen** [comment]
We still have to rerun the models though

**Comment by KennethEnevoldsen** [comment]
#127 reran coheres (and it seems to indeed improve as expected)

**Comment by KennethEnevoldsen** [comment]
Added a while back
