### ISSUE TITLE
CLI average score NaN

### ISSUE THREAD

**Issue by x-tabdeveloping** [KennethEnevoldsen/scandinavian-embedding-benchmark#122]
When not all tasks have been run for all models, then the average becomes NaN. This will supposedly not be an issue in the future when we've run everything and the cache contains all results, but it is rather annoying. It's also a bit hard comparing the models when most of them are missing tasks.
My idea for fixing the NaN issue is simply `np.nanmean`

Do you have an idea for the comparison table so that models can still be compared when not all tasks are run for all of them? Should we perhaps order after average rank instead of average score?

**Comment by KennethEnevoldsen** [comment]
I would prefer that it is NaN (indicating that not all tasks have been run)

Average ranks is odd when there is NaN (the model essentially gets lowest score). 

I am currently trying to run all models on ucloud so it should be less of an issue.
