### ISSUE TITLE
Fasttext models seems too slow

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#123]
It might be due to the models loading during the encoding process

**Comment by x-tabdeveloping** [comment]
Yeah, the model definitely loads at the first `encode()` call, which happens before we monitor speed. FastText is just hella slow.
I was actually thinking about potentially dropping it for this reason. I have a couple of ideas for what to replace it with it if we want to:
1. Use SpaCy models' `Tok2Vec` layer as it is a bloom embedding, aka way less memory, and is also significantly faster.
2. Package some static word embedding models as SentenceTransformers, as they do [here](sentence-transformers/average_word_embeddings_glove.6B.300d). This would take a bit of time, as we would have to build the models from scratch, but we would need significantly less code in SEB, and would make it easier for others to use and download prepackaged scandinavian word embeddings.
3. Use Gensim with hand-picked static word embedding models. This would have the same result as the SentenceTransformers solution, but would result in more code in SEB as the models have to be downloaded and used.

**Comment by x-tabdeveloping** [comment]
@KennethEnevoldsen do we want to do anything with this beyond removing them from the tests or just close this?

**Comment by KennethEnevoldsen** [comment]
> Yeah, the model definitely loads at the first encode() call, which happens before we monitor speed. FastText is just hella slow.

I right might just be how it should be then. Will close this for now then

**Comment by KennethEnevoldsen** [comment]
re-opening this as it is likely to look suspicious in figure in the paper.

**Comment by x-tabdeveloping** [comment]
I'm not sure it's a bug though, the thing is really damn slow, and again the model loads before the speed test, so the numbers should be accurate. The only thing we can do is choose a different model.

**Comment by KennethEnevoldsen** [comment]
in the #143 I reran the fasttext models. They were waaay faster (nothing changed just reran it), might have been run in debug mode the first time.
