### ISSUE TITLE
Add custom dataset prompt to mistral-e5 + rerun

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#125]
Given #66, we should update mistral-e5.

**Comment by x-tabdeveloping** [comment]
Should this be an attribute of the tasks or the model? I'm guessing task would make sense as we could have different specific prompts for each of them. On the other hand it makes it is a bit tedious to modify the interface and write a prompt for each task separately. What do you think @KennethEnevoldsen ?

**Comment by x-tabdeveloping** [comment]
It seems that in [Microsoft's own code](https://github.com/microsoft/unilm/blob/9c0f1ff7ca53431fe47d2637dfe253643d94185b/e5/utils.py#L106) they do a mapping of task types or names to prompts in the model's file. Should we go with this? They also have some precooked prompts for us to use.

**Comment by KennethEnevoldsen** [comment]
Sounds like a great idea!

**Comment by KennethEnevoldsen** [comment]
Added a while back. Will close for now
