### ISSUE TITLE
Experiment with merging for embedding models

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#126]
We could merge a mistral-e5 (or the new improved version) onto the Danish Munin model.

@x-tabdeveloping

**Comment by x-tabdeveloping** [comment]
Maybe we should wait with this until the legal issues get resolved (?)

**Comment by KennethEnevoldsen** [comment]
> Maybe we should wait with this until the legal issues get resolved (?)

Feel free to write me on slack regarding this, I will leave it out of this issue though.

I have added a few models to run experiments on:

Two models merged using the adapter layer from mistral-e5:
- https://huggingface.co/KennethEnevoldsen/munin-neuralbeagle-7b-e5
- and one with munin

I will also create a direct merge between mistral-e5 and munin.

We should also get the embeddings of pure munin as a baseline.

**Comment by KennethEnevoldsen** [comment]
We did so in #163, though they weren't highly promising
