### ISSUE TITLE
Add and run multilingual-e5-large-instruct

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#139]
https://huggingface.co/intfloat/multilingual-e5-large-instruct

**Comment by x-tabdeveloping** [comment]
Oh wow, do we even have a chance making models at this rate?

**Comment by KennethEnevoldsen** [comment]
Yea, it goes very fast - and for English I could imagine it is waaaay worse.

**Comment by x-tabdeveloping** [comment]
Adding it in #141 , still needs to be run

**Comment by KennethEnevoldsen** [comment]
Added in latest version
