### ISSUE TITLE
Add paraphrase-multilingual-MiniLM-L12-v2 or another of the MiniLM models

### ISSUE THREAD

**Issue by kwedel** [KennethEnevoldsen/scandinavian-embedding-benchmark#176]
https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

**Comment by KennethEnevoldsen** [comment]
it is already there:

<img width="781" alt="Screenshot 2024-06-20 at 15 06 59" src="https://github.com/KennethEnevoldsen/scandinavian-embedding-benchmark/assets/23721977/afb8a6de-a54f-4675-aa9c-655efdcbf875">

**Comment by kwedel** [comment]
Sorry, I don't know how I managed to miss it.

**Comment by KennethEnevoldsen** [comment]
No worries, if you haven't seen it there is also a plot here on model recommendations: 

https://kennethenevoldsen.github.io/scandinavian-embedding-benchmark/speed_performance/

and it does come in as one of the fastest with a decent performance. That being said the multilingual e5 models is a solid performance improvement.

**Comment by kwedel** [comment]
I hadn’t seen that either. Very nice overview!Yes, I see that it does lie on the Pareto frontier, but with a larger emphasis on speed than performance compared to the e5 family. Thanks for the tip. Den 21. jun. 2024 kl. 08.54 skrev Kenneth Enevoldsen ***@***.***>:﻿
No worries, if you haven't seen it there is also a plot here on model recommendations:
https://kennethenevoldsen.github.io/scandinavian-embedding-benchmark/speed_performance/
and it does come in as one of the fastest with a decent performance. That being said the multilingual e5 models is a solid performance improvement.
