### ISSUE TITLE
Compatibility with Python 3.8

### ISSUE THREAD

**Issue by x-tabdeveloping** [KennethEnevoldsen/scandinavian-embedding-benchmark#34]
This might not necessarily be an issue as we can run stuff elsewhere, but UCloud GPU instances run on a virtual machine that only has Python 3.8. The package cannot even be installed.

Should we rewrite, so that this isn't a problem or just run the benchmarks elsewhere?

**Comment by KennethEnevoldsen** [comment]
3.8 is at end of life, wouldn't want to maintain it. We should fix it at UCloud (they shouldn't use 3.8)
