### ISSUE TITLE
mistral e5  model does not work (or is too slow)

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#42]
The mistral e5  model does not work (or is too slow) to be applied. The model as added in #40 

@x-tabdeveloping I see that you have implemented it using sentence transformers, but the model [description](https://huggingface.co/intfloat/e5-mistral-7b-instruct) does not use a sentence transformer. Have you tested it out?

**Comment by x-tabdeveloping** [comment]
I have tested it (on a 32 core CPU instance on Ucloud) and it should work. I'm suspecting the issue is the model size, and it simply can't run on Github actions.

**Comment by KennethEnevoldsen** [comment]
Oh I just ran in on my laptop. Will try with a Ucloud instance as well, might have been too slow due to it trying to offload the model to memory.

**Comment by KennethEnevoldsen** [comment]
Having run the model on UCloud it obtain very poor performance. I have updated it following the official recommended implementation. I will run it again to see if it matches.
