### ISSUE TITLE
Add a column for speed

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#53]
Add a column for speed.
We can run all models on UCloud for a fair comparison.

This would essentially be a new (mini) benchmark. The result should also be save in cache. I believe the relevant metadata:

Speed ms
system
python version
seb version

This should be done on some sample dataset (potentially of small and increasing larger documents).

**Comment by x-tabdeveloping** [comment]
Isn't import time going to be a problem with some things?
Since Fasttext is not a dependency by default for example, the model needs to download the first time `encode()` is called.

**Comment by x-tabdeveloping** [comment]
Alrighty I will do that. Wouldn't that break things though if we're running on a computer that does not have fasttext installed, or would it just hit cache instantly and not initialize the object?

**Comment by KennethEnevoldsen** [comment]
The encoder is not initialized as long as cache is hit (due to the seb.EmbeddingModel previously called SebModel)

The naming is a bit weird here, feel free to suggest a different naming scheme for differentiating the model with the dynamic loading + metadata from the encoder interface.

**Comment by x-tabdeveloping** [comment]
@KennethEnevoldsen is this still an issue, or can we close it?

**Comment by KennethEnevoldsen** [comment]
No we can close it
