### ISSUE TITLE
Add pretty printing or some displaying to the CLI.

### ISSUE THREAD

**Issue by x-tabdeveloping** [KennethEnevoldsen/scandinavian-embedding-benchmark#59]
It would be nice if the CLI didn't only save results but also presented the results in some human-readable way.
I'm thinking either a HTML table in a browser tab or a rich/tabular table in the command line.

**Comment by KennethEnevoldsen** [comment]
sure thing! Was a bit unsure of how we wanted it to look like. Now that you have all the stuff from the cache it is very easy to generate a full table or any sort of subsection of it. It also allow computing stuff like rank. Probably a good idea to just outline what we want before we develop it

**Comment by x-tabdeveloping** [comment]
My idea was that we could have a full table akin to the one on the website (except for the fasceting) and highlight the model the user has just run. I started toying around with this in rich, as it makes the nicest tables in my experience.

**Comment by KennethEnevoldsen** [comment]
Rich is pretty. Perfectly fine with that. It also seems like a great idea to allow the user to write to table to csv (but I suppose they can just download the one on the webpage).

**Comment by x-tabdeveloping** [comment]
![Screenshot from 2024-01-15 14-51-28](https://github.com/KennethEnevoldsen/scandinavian-embedding-benchmark/assets/13087737/cb3cb0d0-1a18-44c6-adae-a2e04c747eb5)
This. I still gotta tinker around with it a bit more.

**Comment by x-tabdeveloping** [comment]
We could also add a CLI command for just displaying this, then people can display the results that they already got from running the CLI.

**Comment by x-tabdeveloping** [comment]
or we could wrap the table into multiple tables if we want to see everything no matter what

**Comment by x-tabdeveloping** [comment]
what do you think?

**Comment by KennethEnevoldsen** [comment]
> Maybe we could make it better still by only displaying the rows around the newly made model and discard the rest

Considered something like this, but the you should add an index column. Probably also worth to see the best model.

> We could also add a CLI command for just displaying this, then people can display the results that they already got from running the CLI.

Hmm that might be relevant, it is now possible to "run" the benchmark without running any models. So it should def. be possible. Then I would create print the scores only for the 

seb run --> only prints score for current model

seb compare (or another name) --> print table with only nearby models

**Comment by x-tabdeveloping** [comment]
How about we have two tables? One where we show all results of the model we just have run and then one where we show where it is placed in the "hierarchy" maybe showing the 3 highest ranking ones and then 2 or 3 on each side of the current model. The index we already have in the table btw

**Comment by x-tabdeveloping** [comment]
![Screenshot from 2024-01-16 11-17-57](https://github.com/KennethEnevoldsen/scandinavian-embedding-benchmark/assets/13087737/40af10f1-b7d6-4808-ba1c-c514c6bd4f72)

This?

**Comment by x-tabdeveloping** [comment]
And of course it shows the whole thing when there is space for it.

**Comment by KennethEnevoldsen** [comment]
Looks good!

**Comment by x-tabdeveloping** [comment]
Do we want two tables? Or should we just roll with one?

**Comment by KennethEnevoldsen** [comment]
You decide what you think flows best (it might also be better as a flag). Then we can take it in the PR

**Comment by KennethEnevoldsen** [comment]
This was added in #68

**Comment by x-tabdeveloping** [comment]
After the tests have been fixed and you merged the PR, the selected models are no longer highlighted.

**Comment by KennethEnevoldsen** [comment]
I seem to get a duplicate of the model, but otherwise, it seems like it works
![Screenshot 2024-01-22 at 10 58 51](https://github.com/KennethEnevoldsen/scandinavian-embedding-benchmark/assets/23721977/bb3b111f-15e8-43a9-90a8-c18cc585428f)

**Comment by KennethEnevoldsen** [comment]
Added a PR #74 which fixes the duplicate entries - let me know if the highlight doesn't work

**Comment by x-tabdeveloping** [comment]
huh, strange, I will try to pull the new one and see

**Comment by x-tabdeveloping** [comment]
New problem is: If I do not specify any models, it just highlights everything. Also the dividing line between the first three and all else is still there when the whole table is printed.

**Comment by KennethEnevoldsen** [comment]
@x-tabdeveloping is this still an issue? It all works as intended here

**Comment by x-tabdeveloping** [comment]
Closing, as it has been addressed
