### ISSUE TITLE
Datasets to add

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#61]
We are still missing a few datasets. I believe these can fill out the ranks and cover most use-cases for Scandinavian languages.

- [x] ~~[NordJylland News](https://huggingface.co/datasets/alexandrainst/nordjylland-news-summarization) , STS~~
- [x] #116
- [x] #83
- [x] ~~VGSummerization, STS~~
- [x] ~~[SNL](https://huggingface.co/datasets/navjordj/SNL_summarization), sts~~
- [x] #111
- [x] #112
- [x] #115
- [x] #114
- [x] #63
- [x] Add #54 
- [x] #93

We notably need 
- bitext for Swedish
-  clustering for Danish

(before running model we should probably consider implementing #18 and #94). 

- edit: removed STS tasks (see #101 )

**Comment by KennethEnevoldsen** [comment]
@x-tabdeveloping I believe these datesets mostly cover what we want in SEB? Let me know if there is anything specifically that we are missing.

**Comment by x-tabdeveloping** [comment]
I'm sure we can get some Bitext mining task for Swedish from OPUS like swedish-norwegian or swedish-danish, I can do that if need be.

**Comment by x-tabdeveloping** [comment]
Could we perchance use (aka. scrape or find) DBA entries and categories for Danish clustering?

**Comment by KennethEnevoldsen** [comment]
> Could we perchance use (aka. scrape or find) DBA entries and categories for Danish clustering?

We could, I am unsure if we could share the dataset though.

**Comment by KennethEnevoldsen** [comment]
A simpler solution might be to simply use dagw domains.

**Comment by KennethEnevoldsen** [comment]
I have split up all the datasets to add into issues for now. Unless we specifically want to add some new dataset I believe we can close this issue.

**Comment by KennethEnevoldsen** [comment]
Ah there might be a review sentiment dataset available here: https://github.com/esbenkc/Emma

**Comment by KennethEnevoldsen** [comment]
There is also this intent classification dataset from Certainly.io: https://github.com/certainlyio/corona_dataset/blob/master/danish.csv

**Comment by x-tabdeveloping** [comment]
jolly, let's close this
