### ISSUE TITLE
Add norwegian bitext (already added to mteb)

### ISSUE THREAD

**Issue by x-tabdeveloping** [KennethEnevoldsen/scandinavian-embedding-benchmark#63]

**Comment by x-tabdeveloping** [comment]
Just add the Nynorsk-Bokmål bitext task from MTEB

**Comment by x-tabdeveloping** [comment]
The problem is, we would need a new release of MTEB to just add it from there, no? @KennethEnevoldsen

**Comment by KennethEnevoldsen** [comment]
If we can bump to the latest mteb version that is a simple fix. Otherwise I would just copy over the code and then transition to the MTEB version once SEB is stable.
