### ISSUE TITLE
Add custom embedding to e5-models

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#75]

**Comment by x-tabdeveloping** [comment]
@KennethEnevoldsen Can you confirm that this has not been addressed yet? In that case I will get on it.

**Comment by x-tabdeveloping** [comment]
We have a bit of an interface problem here unfortunately: Only the task is getting passed along to the embedding model, not whether the current document is a query or a passage, even though that's the only case where we can use custom embeddings for E5. How should we go about fixing this? @KennethEnevoldsen

**Comment by KennethEnevoldsen** [comment]
Right... I am actually unsure. @Muennighoff how is this handled in MTEB (I believe atm it is not handled but I might be wrong).

One solution is to monkey-patch the evaluation functions. Though that is not as clean.

**Comment by Muennighoff** [comment]
It is handled in MTEB via separate encode_corpus & encode_queries functions (https://github.com/embeddings-benchmark/mteb/blob/d292d937ceedb5d137537b2c25a0f135d1bb91b9/mteb/abstasks/AbsTaskRetrieval.py#L106)

See how they do it for E5 here: https://github.com/microsoft/unilm/blob/9c0f1ff7ca53431fe47d2637dfe253643d94185b/e5/mteb_beir_eval.py#L39

**Comment by KennethEnevoldsen** [comment]
Ahh I see so if the model implements the `encode_corpus` and `encode_queries` methods we should be golden.

btw the line:
```python
self.is_dres_compatible(model)
```

Seems like it could be replaced by a protocol. Which then would make the code `isinstance(Model, DRESModelInterface)`.

**Comment by x-tabdeveloping** [comment]
Okay I will get on it then

**Comment by KennethEnevoldsen** [comment]
> is_dres_compatible is only supposed to check for whether those two methods exist (i.e. it does not even need to inherit from DRESModel as long as it has an encode_corpus & encode_queries func)

Which is the use case for a protocol (no need to change anything just wanted to let you know that the protocol object solves that particular use case). It just specifies an interface of an object (it should have an encode_corpus and encode_queries method).

**Comment by Muennighoff** [comment]
> > is_dres_compatible is only supposed to check for whether those two methods exist (i.e. it does not even need to inherit from DRESModel as long as it has an encode_corpus & encode_queries func)
> 
> Which is the use case for a protocol (no need to change anything just wanted to let you know that the protocol object solves that particular use case). It just specifies an interface of an object (it should have an encode_corpus and encode_queries method).

Oh I see, feel free to change it if you think it's better but can also leave as is, I don't mind 👍

**Comment by x-tabdeveloping** [comment]
I would generally prefer to keep things simple as a rock just to chime in on the debate, so I think I would prefer
```python
hasattr(this_dude, "encode_something") and hasattr(this_dude, "encode_some_other_thing")
```
over a protocol mostly because it's easier on your eye. You don't have to look a million places to figure out what is _actually_ happening when the code is run.

I believe an even more Pythonic move would be to just try-catch it, easier to ask for forgiveness rather than permission:
```python
try:
    model.encode_this()
    model.encode_that()
except AttributeError:
    model.encode()
```

Though protocols give you better static type checking so I also see why it would be beneficial to have that.

**Comment by KennethEnevoldsen** [comment]
Just an excuse to talk about protocols - no need to change anything.

@x-tabdeveloping The benefit of using a protocol over this approach is that you can type-hint it.

**Comment by x-tabdeveloping** [comment]
Yes yes, I mentioned that last line :D

**Comment by KennethEnevoldsen** [comment]
Ahh yes sorry
