### ISSUE TITLE
Any models that we need to add?

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#79]
@x-tabdeveloping  and @Muennighoff, are there any representative models that we need to add before a publication?

I could see mBERT and XLM-R as naive multilingual encoder baselines (xlm-r would probably be enough) (#81)

**Comment by Muennighoff** [comment]
I suggest adding LaBSE, especially for the Bitext Mining tasks as it's No 1 for English-X but we don't have it for Danish Bitext Mining. It's also not bad on other multilingual tasks

**Comment by KennethEnevoldsen** [comment]
Yea LaBSE is a solid model to add (#80)

**Comment by x-tabdeveloping** [comment]
I have a couple of suggestions:
 - [Voyage](https://docs.voyageai.com/embeddings/), because they perform very well on MTEB and they also have some of their own benchmarking datasets, on which they outperform a lot of models that do fine on MTEB
 - [Jina](https://huggingface.co/jinaai/jina-embedding-b-en-v1) because it has 8000 context length.

**Comment by KennethEnevoldsen** [comment]
Both sound like great candidates. Feel free to add those as well.

**Comment by x-tabdeveloping** [comment]
I think we need to get an API key from Voyage, maybe we could ask them to give us a free one as we're using it for research purposes. I can do that if that sounds good to you.

**Comment by KennethEnevoldsen** [comment]
Sounds perfect. Send a mail. It is an English model as I understand so it is not the most important model (though it seems like it performs quite well)

**Comment by x-tabdeveloping** [comment]
Email sent. Waiting for the response :)

**Comment by x-tabdeveloping** [comment]
We might also consider adding the AngLE model due to its high performance on MTEB.

**Comment by KennethEnevoldsen** [comment]
We can def. add an embedding model

I believe we should at least add a few baseline model for the dataset (simcse, angleIE). We already have the simcse. 

@Muennighoff You mentioned that you had some ideas as well?

**Comment by Muennighoff** [comment]
Do you mean ideas regarding more models besides labse etc?

**Comment by KennethEnevoldsen** [comment]
Ahh sorry misunderstood @x-tabdeveloping. Thought he wanted to train an embedding model.

**Comment by KennethEnevoldsen** [comment]
Will close this for now. @x-tabdeveloping feel free to open a PR/issue for the angIE models
