### ISSUE TITLE
Add translate and embed baselines

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#8]
For translation:
https://huggingface.co/facebook/m2m100_1.2B

or the helsinki one

**Comment by x-tabdeveloping** [comment]
I'm also wondering whether an LLM would perform better at this. My intuition is that they are relatively good at understanding Nordic languages, but are not very good at writing. In Facebook's model one has to specify the source language but some tasks are multilingual as far as I understand it, so it's not  trivial which language should be chosen in that case.
It could be the case that Swedish would still work fine if we choose Danish as a source language, but then I could also see an LLM being able to handle all languages in one basket a bit better.

**Comment by x-tabdeveloping** [comment]
@KennethEnevoldsen If the task specifies multiple languages, I fall back to the first one, and if none are specified I fall back to Danish as the source language for the translation. Is that a fair compromise, or how should I go about this?

**Comment by x-tabdeveloping** [comment]
Unfortunately if we wanted to do this proper, we would also need a model for language identification, which is a bit of an overkill I think.

**Comment by x-tabdeveloping** [comment]
Or well if we want to do that, I think this is a reasonably fast solution: https://huggingface.co/facebook/fasttext-language-identification

**Comment by KennethEnevoldsen** [comment]
> @KennethEnevoldsen If the task specifies multiple languages, I fall back to the first one, and if none are specified I fall back to Danish as the source language for the translation. Is that a fair compromise, or how should I go about this?

Oh you are right. We actually need identification...

**Comment by x-tabdeveloping** [comment]
Yeah I will go with the Heuristic. I also experimented a bit with language identification, and it works okay for the mainland languages, but Bornholmsk is detected as something entirely different (not even germanic) which could cause issues on its own.

**Comment by x-tabdeveloping** [comment]
Addressed by #85
