### ISSUE TITLE
add XLM-R 

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#81]

**Comment by x-tabdeveloping** [comment]
We want both models, right?
 - `FacebookAI/xlm-roberta-base`
 - `FacebookAI/xlm-roberta-large`

**Comment by x-tabdeveloping** [comment]
Wait a sec, we already have `xlm-roberta-base` in the benchmark, am I missing something?

**Comment by x-tabdeveloping** [comment]
Currently we use mean pooling on it, but `sentence-transformers/LaBSE` uses the `[CLS]` token, which makes a lot of sense, should we not do that on XLM-R as well?
