### ISSUE TITLE
Add word embedding baseline 

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#9]

**Comment by x-tabdeveloping** [comment]
I think we could either do this with initializing an embedding layer and then adding pooling and packaging it as a sentence transformer, then we don't have to tinker with our code, or just Gensim it.

**Comment by KennethEnevoldsen** [comment]
Def. just use a pertained glove vector or something similar. We can add gensim as an optional dependency.

**Comment by x-tabdeveloping** [comment]
Adressed by #85
