### ISSUE TITLE
restructure tasks and classes

### ISSUE THREAD

**Issue by KennethEnevoldsen** [KennethEnevoldsen/scandinavian-embedding-benchmark#99]
@x-tabdeveloping suggest:

> We could also potentially fix the task situation by making all Encoder-s have a task attribute.
> Then instead of EmbeddingModel we would have an ModelLoader:
> ```python
> class Encoder(Protocol):
>      task: Task
>      
>      def encode(self, sentences: list[str], **kwargs):
>           pass
>     # And then optionally the other two methods
> 
> @dataclass
> class ModelLoader:
>     meta: ModelMeta
>     loader: Callable[[Task], Encoder]
>     
> class Task(Protocol):
>      def evaluate(self, loader: ModelLoader) -> TaskResult:
>           model = loader(self)
>           ...
> ```

I agree with there being something here that is not right.

I don't believe the model should be loaded in the task though, this leads to a few issue:
- The task conceptually shouldn't change the state of the model (except for the task of course)
- It is inefficient to load the model many times (especially for larger models, where it takes a while)

An alternative might be to do:
`model.set_task(task)`
and the unset the task at the end. This could be done in the run_task or in task.evaluate function.

I also totally agree that we should make sure the differentiate the "loader + metadata" from the encoder in a meaningful way.

**Comment by KennethEnevoldsen** [comment]
The `run_task` could also be the one that actually loads the model and hands it the task information.

**Comment by x-tabdeveloping** [comment]
Hmm my functional programming monke :monkey: brain does not like `model.set_task(task)`. I would prefer to avoid state changes in code everywhere when possible. Could we not do some closure/currying kinda thing to make this work?

**Comment by KennethEnevoldsen** [comment]
Hmm something like:

```python
def run_task(loader, task):
  mdl = loader.load_model(task=task)
  
class Loader():
  def load_model(task):
    if self.model_is_loaded:
      self.model.task = task
      return self.model
   else:
        return self._load_model(task)
```

**Comment by KennethEnevoldsen** [comment]
Hmm actually a structure somewhat like this seems meaningful:

```python

class Encoder():
   "the encoder - the object in charge of all the encoding needs"
   
   # ideally it shouldn't have a state for task, but only be informed of it here (as well as other encode methods:
   def encode(... task: Task):
      ...
   

class ModelLoader():
   "dynamic loading of models"
   ...
   
def SebModel():  # not sure I like the name - especially as it would be seb.SebModel
   "the object that gets passed around"
   loader: ModelLoader
   meta: ModelMeta
```

Since we can't change the code in MTEB, we need to have some way of passing the task to the encode methods. This is the reason for the MTEBTaskModel. Which worked like a partial but for the class. It might be smarter to "overwrite" the encode method.

A smarter way in the MTEBTask might be to do:

```python
original_encode = model.encode()

model.encode = partial(original_encode, task=task)
mteb_task.evaluate(model)
model.encode = original_encode
```

**Comment by KennethEnevoldsen** [comment]
We discussed in meeting, something like this:

SebModel:
  model: Encoder
  meta: ModelMeta
 LazyLoadEncoder(Encoder)
   …
   def encode():

**Comment by x-tabdeveloping** [comment]
@KennethEnevoldsen Pydantic fucks us over a bit. 
```
  File "/home/au689890/Documents/Github/scandinavian-embedding-benchmark/src/seb/interfaces/mteb_task.py", line 73, in evaluate
    model.encode = partial(model.encode, task=self)
  File "/home/au689890/anaconda3/envs/seb/lib/python3.9/site-packages/pydantic/main.py", line 789, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "EmbeddingModel" object has no field "encode"
```

**Comment by KennethEnevoldsen** [comment]
convert it to a python dataclass instead

**Comment by x-tabdeveloping** [comment]
@KennethEnevoldsen I'm thinking it would actually not be stupid to do a shallow copy of the model object and override the encode method. That way we wouldn't have to do all this gymnastics with the try-catch blocks and all

**Comment by KennethEnevoldsen** [comment]
So do you suggest an MTEBTaskModel?

**Comment by x-tabdeveloping** [comment]
No, because MTEBTaskModel would not by default have the same attributes (encode_query, encode_documents) so it is not the same. What I mean is a new object that has the same attributes but we overwrite encode with the partial

**Comment by x-tabdeveloping** [comment]
My concerns have been addressed by the merged pull request, I'm closing the issue.
